Add description to vhosts config file; #8

diff --git a/bin/project-analyser b/bin/project-analyser
--- a/bin/project-analyser
+++ b/bin/project-analyser
@@ -201,7 +201,18 @@ if $WRITE_VHOSTS_CONFIG_FILE; then
     done
 
     # write config file
+    date=$(date +"%Y-%m-%d %H:%M:%S")
+    version=$(getRepositoryVersion "$pathRoot" true)
+
     echo -n "" > $CONFIG_FILE
+
+    echo "# This file was automatically generated by $scriptname ($version)" >> $CONFIG_FILE
+    echo "# via: $FULL_COMMAND_LINE"                                         >> $CONFIG_FILE
+    echo "#"                                                                 >> $CONFIG_FILE
+    echo "# @date    $date"                                                  >> $CONFIG_FILE
+    echo "# @version 1.0"                                                    >> $CONFIG_FILE
+    echo ""                                                                  >> $CONFIG_FILE
+
     for targetUri in "${!urlContainer[@]}"; do
         url="${urlContainer[$targetUri]}"
         servername="${servernameContainer[$targetUri]}"
@@ -238,7 +249,7 @@ if ! $ANALYSE_VIRTUAL_HOSTS; then
 
     # the current config was not found within the config file $CONFIG_FILE
     if ! $configFound; then
-        echo "The current config $currentConfig was not found within the config file \"$CONFIG_FILE\". Abort.." && exit 0
+        echo "The current config $currentConfig was not found within the config file \"$CONFIG_FILE\". Abort.." && exit 1
     fi
 
     $currentConfig
